<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmailDomainSeeder extends Seeder
{
    public function run(): void
    {
        $domains = [
            [
                'name' => 'dropit.io',
                'display_name' => 'DropIt',
                'type' => 'free',
                'status' => 'active',
                'is_system' => true,
                'mx_verified' => true,
                'priority' => 1,
                'health_score' => 100,
                'blocked_score' => 2,
                'features' => json_encode(['email' => true, 'alias' => true, 'otp' => true, 'attachments' => true, 'autoDelete' => true, 'fastDelivery' => true]),
                'acceptance' => 5,
                'best_for' => json_encode(['Social Media', 'Newsletters', 'Verification']),
                'restrictions' => '',
                'popular' => true,
                'exclusive' => false,
            ],
            [
                'name' => 'burnbox.dev',
                'display_name' => 'BurnBox',
                'type' => 'free',
                'status' => 'active',
                'is_system' => true,
                'mx_verified' => true,
                'priority' => 2,
                'health_score' => 98,
                'blocked_score' => 5,
                'features' => json_encode(['email' => true, 'alias' => true, 'otp' => true, 'attachments' => true, 'autoDelete' => true, 'fastDelivery' => true]),
                'acceptance' => 4,
                'best_for' => json_encode(['Testing', 'Development', 'CI/CD']),
                'restrictions' => '',
                'popular' => false,
                'exclusive' => false,
            ],
            [
                'name' => 'zaptmp.net',
                'display_name' => 'ZapTmp',
                'type' => 'free',
                'status' => 'active',
                'is_system' => true,
                'mx_verified' => true,
                'priority' => 3,
                'health_score' => 95,
                'blocked_score' => 8,
                'features' => json_encode(['email' => true, 'alias' => false, 'otp' => true, 'attachments' => false, 'autoDelete' => true, 'fastDelivery' => true]),
                'acceptance' => 4,
                'best_for' => json_encode(['Quick Signups', 'OTP Codes', 'Social Media']),
                'restrictions' => '',
                'popular' => false,
                'exclusive' => false,
            ],
            [
                'name' => 'voidmail.cc',
                'display_name' => 'VoidMail',
                'type' => 'free',
                'status' => 'active',
                'is_system' => true,
                'mx_verified' => true,
                'priority' => 4,
                'health_score' => 92,
                'blocked_score' => 12,
                'features' => json_encode(['email' => true, 'alias' => true, 'otp' => false, 'attachments' => false, 'autoDelete' => true, 'fastDelivery' => true]),
                'acceptance' => 3,
                'best_for' => json_encode(['Privacy', 'One-off Use', 'Aliases']),
                'restrictions' => 'Some banking websites may reject this domain.',
                'popular' => false,
                'exclusive' => false,
            ],
            [
                'name' => 'mailsink.app',
                'display_name' => 'MailSink',
                'type' => 'free',
                'status' => 'active',
                'is_system' => true,
                'mx_verified' => true,
                'priority' => 5,
                'health_score' => 100,
                'blocked_score' => 0,
                'features' => json_encode(['email' => true, 'alias' => true, 'otp' => true, 'attachments' => true, 'autoDelete' => true, 'fastDelivery' => true]),
                'acceptance' => 5,
                'best_for' => json_encode(['Social Media', 'Shopping', 'AI Tools']),
                'restrictions' => '',
                'popular' => true,
                'exclusive' => false,
            ],
            [
                'name' => 'secureinbox.io',
                'display_name' => 'SecureInbox',
                'type' => 'pro',
                'status' => 'active',
                'is_system' => true,
                'mx_verified' => true,
                'priority' => 6,
                'health_score' => 100,
                'blocked_score' => 0,
                'features' => json_encode(['email' => true, 'alias' => true, 'otp' => true, 'attachments' => true, 'autoDelete' => true, 'fastDelivery' => true]),
                'acceptance' => 5,
                'best_for' => json_encode(['Banking', 'Finance', 'Business']),
                'restrictions' => '',
                'popular' => false,
                'exclusive' => false,
            ],
            [
                'name' => 'privmail.net',
                'display_name' => 'PrivMail',
                'type' => 'pro',
                'status' => 'active',
                'is_system' => true,
                'mx_verified' => true,
                'priority' => 7,
                'health_score' => 99,
                'blocked_score' => 1,
                'features' => json_encode(['email' => true, 'alias' => true, 'otp' => true, 'attachments' => true, 'autoDelete' => true, 'fastDelivery' => true]),
                'acceptance' => 5,
                'best_for' => json_encode(['Privacy', 'Legal', 'Sensitive Accounts']),
                'restrictions' => '',
                'popular' => false,
                'exclusive' => false,
            ],
            [
                'name' => 'flashbox.dev',
                'display_name' => 'FlashBox',
                'type' => 'pro',
                'status' => 'active',
                'is_system' => true,
                'mx_verified' => true,
                'priority' => 8,
                'health_score' => 100,
                'blocked_score' => 0,
                'features' => json_encode(['email' => true, 'alias' => true, 'otp' => true, 'attachments' => true, 'autoDelete' => true, 'fastDelivery' => true]),
                'acceptance' => 5,
                'best_for' => json_encode(['Development', 'APIs', 'Automation']),
                'restrictions' => '',
                'popular' => false,
                'exclusive' => true,
            ],
            [
                'name' => 'shieldmail.org',
                'display_name' => 'ShieldMail',
                'type' => 'pro',
                'status' => 'active',
                'is_system' => true,
                'mx_verified' => true,
                'priority' => 9,
                'health_score' => 100,
                'blocked_score' => 0,
                'features' => json_encode(['email' => true, 'alias' => true, 'otp' => true, 'attachments' => true, 'autoDelete' => true, 'fastDelivery' => true]),
                'acceptance' => 5,
                'best_for' => json_encode(['Enterprise', 'Government', 'Professional Use']),
                'restrictions' => '',
                'popular' => false,
                'exclusive' => false,
            ],
        ];

        foreach ($domains as $domain) {
            DB::table('email_domains')->updateOrInsert(
                ['name' => $domain['name']],
                array_merge($domain, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
