<?php

namespace Database\Seeders;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\SeoPage;

class SeoPageSeeder extends Seeder
{
    // php artisan db:seed --class=SeoPageSeeder
    public function run()
    {
        $pages = [
            [
                'slug'             => 'temporary-email',
                'title'            => 'Temporary Email – Free Instant Disposable Inbox | inboxOro',
                'meta_description' => 'Get a free temporary email instantly. No signup needed. Receive OTPs, verification links & more. Auto-deletes in 10 minutes. Try inboxOro now.',
                'h1'               => 'Free Temporary Email — Ready in One Second',
                'intro_text'       => '<p>inboxOro generates a disposable temporary email address instantly — no registration, no password, no hassle. Use it for signups, OTP codes, or any site you don\'t fully trust, and let it vanish automatically after 10 minutes.</p>',
                'faq'              => json_encode([
                    ['question' => 'What is a temporary email address?', 'answer' => 'A temporary email is a short-lived, disposable inbox you can use instead of your real email. It receives messages normally but auto-deletes after a set time, protecting your privacy.'],
                    ['question' => 'Is inboxOro completely free?', 'answer' => 'Yes. inboxOro is 100% free with no signup, no credit card, and no hidden fees.'],
                    ['question' => 'How long does my temporary email last?', 'answer' => 'Every inboxOro address and all its emails are automatically deleted after 10 minutes.'],
                    ['question' => 'Can I receive OTP and verification codes?', 'answer' => 'Absolutely. inboxOro receives all standard emails including OTP codes, verification links, and welcome emails in real time.'],
                    ['question' => 'Will using a temp email protect my privacy?', 'answer' => 'Yes. Since you never reveal your real email, you stay anonymous and avoid spam, data breaches, and unwanted marketing.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'disposable-email',
                'title'            => 'Disposable Email – Instant, Private & Free | inboxOro',
                'meta_description' => 'Need a disposable email? inboxOro creates one in seconds — no signup, no spam, auto-deletes in 10 min. Perfect for any online registration.',
                'h1'               => 'Disposable Email Address — Protect Your Inbox Today',
                'intro_text'       => '<p>A disposable email from inboxOro keeps your personal inbox clean and private. Generate one instantly, use it for any signup or verification, and it self-destructs in 10 minutes.</p>',
                'faq'              => json_encode([
                    ['question' => 'What makes a disposable email different from a regular one?', 'answer' => 'A disposable email is temporary and anonymous — it requires no registration and is destroyed after use, unlike a permanent email account.'],
                    ['question' => 'Is a disposable email address legal to use?', 'answer' => 'Yes. Using a disposable email is completely legal and widely recommended for protecting your privacy online.'],
                    ['question' => 'Can websites detect disposable emails?', 'answer' => 'Some sites attempt to block known disposable domains, but inboxOro regularly rotates domains to maintain high deliverability.'],
                    ['question' => 'Do I need to delete the email myself?', 'answer' => 'No. inboxOro automatically deletes everything after 10 minutes — no action required on your part.'],
                    ['question' => 'Can I use a disposable email for PayPal or banking?', 'answer' => 'We recommend using your real email for financial accounts since you\'ll need ongoing access. Disposable emails are best for one-time signups.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'temp-mail',
                'title'            => 'Temp Mail – Free No-Signup Temporary Email | inboxOro',
                'meta_description' => 'Temp mail in one click. inboxOro gives you a real working email address instantly. Receive emails, OTPs & links. No account needed. Auto-expires in 10 min.',
                'h1'               => 'Temp Mail — One Click, Real Inbox, Zero Spam',
                'intro_text'       => '<p>inboxOro\'s temp mail service gives you a fully functional email address the moment you visit — no forms, no passwords. Perfect for quick verifications and keeping your real inbox spotless.</p>',
                'faq'              => json_encode([
                    ['question' => 'Is temp mail the same as a fake email?', 'answer' => 'Not exactly — temp mail is a real, working inbox that receives actual emails. It\'s "temporary" because it expires, not because it\'s fake.'],
                    ['question' => 'How do I get a temp mail address on inboxOro?', 'answer' => 'Just visit inboxOro.com and your temp mail address is automatically generated and displayed — no steps required.'],
                    ['question' => 'Can I choose my own temp mail username?', 'answer' => 'Yes! inboxOro lets you customize the local part of your email address before the @ symbol.'],
                    ['question' => 'Does temp mail work for Gmail verification?', 'answer' => 'Temp mail works for most services. However, Google may require a phone-verified account for some sign-up flows.'],
                    ['question' => 'Is my temp mail inbox private?', 'answer' => 'Yes. inboxOro does not ask for your identity and all emails are purged after 10 minutes.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => '10-minute-mail',
                'title'            => '10 Minute Mail – Self-Destructing Email Address | inboxOro',
                'meta_description' => 'Get a 10 minute mail address free. Receive verification emails and OTPs, then watch it vanish automatically. No signup. Powered by inboxOro.',
                'h1'               => '10 Minute Mail — Instant Inbox That Self-Destructs',
                'intro_text'       => '<p>inboxOro\'s 10-minute mail gives you a working email address that automatically expires after exactly 10 minutes — ideal for one-time signups, trials, and OTP codes without leaving a trace.</p>',
                'faq'              => json_encode([
                    ['question' => 'Does the email really auto-delete after 10 minutes?', 'answer' => 'Yes. Both the email address and every message inside are permanently deleted after 10 minutes with no recovery possible.'],
                    ['question' => 'Can I get a new 10-minute address if mine expires?', 'answer' => 'Absolutely. Just click "Generate New" on inboxOro and a fresh 10-minute address is created instantly.'],
                    ['question' => 'Why 10 minutes specifically?', 'answer' => 'Ten minutes is enough time to complete most email verifications while minimising the window for your address to be scraped or abused.'],
                    ['question' => 'Will I lose important emails when the 10 minutes are up?', 'answer' => 'Yes, so copy any important content before the timer runs out. For long-term emails, always use your real address.'],
                    ['question' => 'Does 10-minute mail work for Discord?', 'answer' => 'Yes! Many users use inboxOro\'s 10-minute mail to verify Discord accounts quickly and privately.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'burner-email',
                'title'            => 'Burner Email – Throwaway Address for Any Signup | inboxOro',
                'meta_description' => 'Create a burner email in seconds with inboxOro. No registration, no trace. Use it once, let it burn. Ideal for trials, forms & one-time verifications.',
                'h1'               => 'Burner Email — Use It Once, Let It Disappear',
                'intro_text'       => '<p>A burner email from inboxOro works exactly like a burner phone — one-time use, completely anonymous, and gone before anyone can trace it back to you.</p>',
                'faq'              => json_encode([
                    ['question' => 'What is a burner email address?', 'answer' => 'A burner email is a throwaway address you use for a single purpose — a signup, a download, a trial — then discard without any connection to your real identity.'],
                    ['question' => 'Is a burner email the same as a temp email?', 'answer' => 'They\'re used interchangeably. Both refer to short-lived, disposable email addresses you use to avoid spam and protect privacy.'],
                    ['question' => 'Can I use a burner email for free trials?', 'answer' => 'Yes! Burner emails are perfect for signing up for free trials without handing over your real email and risking future marketing emails.'],
                    ['question' => 'How anonymous is inboxOro\'s burner email?', 'answer' => 'Very. inboxOro doesn\'t require any personal information, and all data is deleted after 10 minutes.'],
                    ['question' => 'Can a burner email receive attachments?', 'answer' => 'Yes, inboxOro supports incoming emails with attachments during the active 10-minute window.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'fake-email',
                'title'            => 'Fake Email Generator – Real Inbox, Zero Commitment | inboxOro',
                'meta_description' => 'Generate a fake email that actually works. inboxOro gives you a real inbox for OTPs, signups & verifications — no personal info needed. Auto-deletes in 10 min.',
                'h1'               => 'Fake Email Generator — Real Inbox, No Strings Attached',
                'intro_text'       => '<p>inboxOro\'s fake email generator creates an address that looks and behaves like a real email — because it is — just without any connection to your identity. Perfect for protecting your privacy online.</p>',
                'faq'              => json_encode([
                    ['question' => 'Is a fake email address actually real?', 'answer' => 'Yes — "fake" refers to the fact that it\'s not your personal email, not that it doesn\'t work. inboxOro addresses receive real emails in real time.'],
                    ['question' => 'Is generating a fake email illegal?', 'answer' => 'No. Using a disposable email for privacy purposes is completely legal. It\'s widely used by security professionals and privacy-conscious users.'],
                    ['question' => 'Will the fake email receive spam?', 'answer' => 'Potentially, but since it auto-deletes in 10 minutes, any spam disappears along with everything else.'],
                    ['question' => 'Can I use a fake email for Instagram?', 'answer' => 'Yes! Many users create secondary Instagram accounts using inboxOro to receive the verification email safely.'],
                    ['question' => 'Does inboxOro store my fake email history?', 'answer' => 'No. inboxOro does not log or store any email history beyond the active 10-minute session.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'temp-mail-for-discord',
                'title'            => 'Temp Mail for Discord – Verify Accounts Instantly | inboxOro',
                'meta_description' => 'Use inboxOro temp mail to verify your Discord account in seconds. No personal email needed. Free, instant, auto-deletes in 10 minutes.',
                'h1'               => 'Temp Mail for Discord — Verify Without Revealing Your Email',
                'intro_text'       => '<p>Need to verify a new Discord account without using your real email? inboxOro generates a temporary inbox that receives Discord\'s verification email instantly, keeping your identity private.</p>',
                'faq'              => json_encode([
                    ['question' => 'Does Discord accept temporary email addresses?', 'answer' => 'Yes, Discord sends verification emails to any valid inbox including temp mail addresses from inboxOro.'],
                    ['question' => 'Can I create multiple Discord accounts with temp mail?', 'answer' => 'You can use a new inboxOro address for each Discord account, since each generates a unique address.'],
                    ['question' => 'How fast does Discord\'s verification email arrive?', 'answer' => 'Usually within seconds. inboxOro\'s live inbox updates in real time so you\'ll see it immediately.'],
                    ['question' => 'Will my Discord account be at risk using a temp email?', 'answer' => 'Discord accounts verified via temp email work normally, but you won\'t be able to recover the account via email later since the address expires.'],
                    ['question' => 'Is using a temp email for Discord against the rules?', 'answer' => 'Always review Discord\'s Terms of Service. inboxOro is a tool for privacy — how you use your accounts is your responsibility.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'temp-mail-for-instagram',
                'title'            => 'Temp Mail for Instagram – Create Accounts Privately | inboxOro',
                'meta_description' => 'Sign up for Instagram without your real email. inboxOro provides a free temp mail to receive Instagram\'s verification code instantly. Auto-deletes in 10 min.',
                'h1'               => 'Temp Mail for Instagram — Private Signups Made Easy',
                'intro_text'       => '<p>Create a new Instagram account privately using a temporary email from inboxOro. Receive Instagram\'s confirmation email in real time without exposing your personal address.</p>',
                'faq'              => json_encode([
                    ['question' => 'Can Instagram detect temp mail addresses?', 'answer' => 'Instagram may block some known disposable domains. inboxOro rotates domains frequently to maintain high acceptance rates.'],
                    ['question' => 'How do I use temp mail to sign up for Instagram?', 'answer' => 'Copy your inboxOro address, paste it in Instagram\'s signup form, then check your inboxOro inbox for the verification email.'],
                    ['question' => 'Will I lose my Instagram account when the email expires?', 'answer' => 'You\'ll lose the ability to recover via email, but your Instagram account itself stays active. Consider adding a phone number for recovery.'],
                    ['question' => 'Can I use the same temp mail for multiple Instagram accounts?', 'answer' => 'No. Each account needs a unique email. Generate a fresh inboxOro address for each Instagram account you create.'],
                    ['question' => 'Is it safe to create Instagram accounts with temp email?', 'answer' => 'It\'s private and anonymous, but always follow Instagram\'s Community Guidelines to keep your accounts in good standing.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'temp-mail-for-facebook',
                'title'            => 'Temp Mail for Facebook – Sign Up Without Your Real Email | inboxOro',
                'meta_description' => 'Use inboxOro temp mail to register on Facebook privately. Instant inbox, no signup required. Receive Facebook\'s verification code in seconds. Auto-deletes in 10 min.',
                'h1'               => 'Temp Mail for Facebook — Anonymous Account Creation',
                'intro_text'       => '<p>Register a Facebook account without giving away your personal email. inboxOro\'s temporary inbox receives Facebook verification emails in real time — no registration, fully private.</p>',
                'faq'              => json_encode([
                    ['question' => 'Does Facebook allow temp email addresses for signup?', 'answer' => 'Facebook sends verification emails to any valid inbox. inboxOro\'s addresses are real inboxes and receive Facebook emails successfully.'],
                    ['question' => 'How quickly does Facebook\'s confirmation email arrive?', 'answer' => 'Typically within a few seconds. inboxOro\'s real-time inbox shows incoming emails the moment they land.'],
                    ['question' => 'What happens to my Facebook account when the temp email expires?', 'answer' => 'Your account remains active, but email-based recovery won\'t work. Link a phone number to keep recovery options available.'],
                    ['question' => 'Can I use a temp email for a Facebook Business Page?', 'answer' => 'Technically yes for the initial verification, but for business use we recommend a permanent email for ongoing notifications and recovery.'],
                    ['question' => 'Is creating a Facebook account with temp mail against the rules?', 'answer' => 'Review Facebook\'s Terms of Service. inboxOro is for privacy — use it responsibly in compliance with Facebook\'s policies.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'temp-mail-for-tiktok',
                'title'            => 'Temp Mail for TikTok – Verify & Stay Private | inboxOro',
                'meta_description' => 'Sign up on TikTok without your personal email. inboxOro gives you a free temp inbox that receives TikTok verification codes instantly. Auto-deletes in 10 minutes.',
                'h1'               => 'Temp Mail for TikTok — Fast Verification, Zero Exposure',
                'intro_text'       => '<p>Whether you\'re creating a secondary TikTok account or just protecting your privacy, inboxOro\'s temporary email receives TikTok\'s verification email in real time — no personal info required.</p>',
                'faq'              => json_encode([
                    ['question' => 'Does TikTok work with temporary email addresses?', 'answer' => 'Yes. TikTok sends a verification code to any working email inbox, including inboxOro\'s temporary addresses.'],
                    ['question' => 'Can I use inboxOro for TikTok on mobile?', 'answer' => 'Yes! inboxOro is fully mobile-friendly. Open it in your phone browser, copy the address, and paste it into TikTok\'s signup screen.'],
                    ['question' => 'How do I get the TikTok verification code?', 'answer' => 'Just watch your inboxOro inbox — TikTok\'s email arrives within seconds and displays the code right inside the message.'],
                    ['question' => 'Will my TikTok account be deleted when the temp email expires?', 'answer' => 'No. Your TikTok account remains active. Only the temporary email inbox is deleted after 10 minutes.'],
                    ['question' => 'Is this useful for creating TikTok creator accounts?', 'answer' => 'For a primary creator account you plan to grow, use a permanent email. For testing or secondary accounts, inboxOro works great.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'temp-mail-for-netflix',
                'title'            => 'Temp Mail for Netflix – Start a Free Trial Privately | inboxOro',
                'meta_description' => 'Use inboxOro temp mail to sign up for Netflix without your real email. Instant inbox, no registration. Receive Netflix verification in seconds. Auto-deletes in 10 min.',
                'h1'               => 'Temp Mail for Netflix — Private Trial Signups',
                'intro_text'       => '<p>Protect your personal inbox when signing up for Netflix. inboxOro provides a temporary email that receives Netflix\'s welcome and verification emails instantly — no account needed on our end.</p>',
                'faq'              => json_encode([
                    ['question' => 'Can I use a temp email to sign up for Netflix?', 'answer' => 'Yes. Netflix sends confirmation emails to any valid inbox, including inboxOro temporary addresses.'],
                    ['question' => 'Does Netflix require a credit card if I use temp mail?', 'answer' => 'Netflix\'s billing requirements are separate from email. A temp email handles the email step; payment details depend on Netflix\'s current offer.'],
                    ['question' => 'Will I be able to reset my Netflix password later?', 'answer' => 'Not via email, since the temp inbox expires. If you plan to keep using Netflix long-term, update to a permanent email after signing up.'],
                    ['question' => 'How soon does Netflix\'s welcome email arrive in inboxOro?', 'answer' => 'Usually within seconds. inboxOro\'s live inbox displays incoming emails in real time.'],
                    ['question' => 'Is using a temp email for Netflix allowed?', 'answer' => 'Always check Netflix\'s Terms of Service. inboxOro is a privacy tool — your use of any service remains your responsibility.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'temp-mail-for-spotify',
                'title'            => 'Temp Mail for Spotify – Free Signups Without Your Real Email | inboxOro',
                'meta_description' => 'Sign up for Spotify anonymously using inboxOro temp mail. Instant inbox, zero spam risk. Receive Spotify\'s verification email in seconds. No account needed.',
                'h1'               => 'Temp Mail for Spotify — Sign Up Anonymously',
                'intro_text'       => '<p>Create a Spotify account without exposing your personal email. inboxOro delivers Spotify\'s verification email to a temporary, auto-deleting inbox — clean, fast, and private.</p>',
                'faq'              => json_encode([
                    ['question' => 'Does Spotify accept temp mail addresses?', 'answer' => 'Spotify sends verification emails to any working inbox. inboxOro\'s addresses are real functioning inboxes that receive Spotify emails.'],
                    ['question' => 'Can I get Spotify Premium with a temp email?', 'answer' => 'You can sign up with a temp email. Spotify Premium requires payment details separately, which is unrelated to your email address.'],
                    ['question' => 'What if I want to recover my Spotify account later?', 'answer' => 'Update your Spotify email to a permanent address in account settings before the temp inbox expires — that way you won\'t lose access.'],
                    ['question' => 'Can I use temp mail for the Spotify family plan?', 'answer' => 'For a long-term family plan, a permanent email is recommended. Temp mail is best for quick, anonymous signups.'],
                    ['question' => 'Is inboxOro\'s temp mail free for Spotify signup?', 'answer' => 'Yes, completely free. No subscription, no account, no credit card required on inboxOro.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'temp-mail-for-reddit',
                'title'            => 'Temp Mail for Reddit – Create Anonymous Accounts | inboxOro',
                'meta_description' => 'Make a Reddit account without your real email. inboxOro provides free temp mail for Reddit verification — instant inbox, real-time updates, auto-deletes in 10 min.',
                'h1'               => 'Temp Mail for Reddit — Anonymous Account, Real Community',
                'intro_text'       => '<p>Keep your Reddit activity separate from your personal identity. inboxOro\'s temporary email receives Reddit\'s verification link in real time — no personal info required, ever.</p>',
                'faq'              => json_encode([
                    ['question' => 'Does Reddit require email verification?', 'answer' => 'Reddit sends a verification email but many features work before verification. Using inboxOro, you can verify instantly and privately.'],
                    ['question' => 'Can I use temp mail for multiple Reddit accounts?', 'answer' => 'Yes. Generate a new inboxOro address for each Reddit account you want to create, since each needs a unique email.'],
                    ['question' => 'Will Reddit ban accounts made with temp email?', 'answer' => 'Reddit\'s rules focus on behaviour, not the type of email used to register. Follow Reddit\'s rules and your account will be fine.'],
                    ['question' => 'How do I verify Reddit with inboxOro?', 'answer' => 'Copy your inboxOro address into Reddit\'s signup form, then open your inboxOro inbox and click the verification link in Reddit\'s email.'],
                    ['question' => 'Can I post and comment on Reddit without email verification?', 'answer' => 'Many subreddits allow unverified accounts to browse and some to post. Verifying with inboxOro gives you full access immediately.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'temp-mail-for-twitter',
                'title'            => 'Temp Mail for Twitter/X – Verify Accounts Privately | inboxOro',
                'meta_description' => 'Sign up for Twitter/X without your personal email. inboxOro delivers a free temp inbox for Twitter verification in seconds. No signup needed. Auto-deletes in 10 min.',
                'h1'               => 'Temp Mail for Twitter / X — Stay Anonymous Online',
                'intro_text'       => '<p>Protect your personal inbox when creating a Twitter or X account. inboxOro\'s temporary email receives Twitter\'s confirmation instantly — real-time inbox, zero registration required.</p>',
                'faq'              => json_encode([
                    ['question' => 'Does Twitter/X accept temp mail for account creation?', 'answer' => 'Yes. Twitter sends verification emails to any valid inbox. inboxOro addresses receive Twitter emails in real time.'],
                    ['question' => 'Will I lose my Twitter account when the temp email expires?', 'answer' => 'Your account stays active, but you won\'t be able to recover it via email. Add a phone number in settings as a backup.'],
                    ['question' => 'Does Twitter require a phone number instead of email?', 'answer' => 'Twitter/X may prompt for a phone number in some regions or for certain account types. Email-only signup is still available in most cases.'],
                    ['question' => 'Can I use inboxOro for a Twitter business account?', 'answer' => 'For a primary business presence, use a permanent company email. For testing or throwaway accounts, inboxOro is ideal.'],
                    ['question' => 'Is creating a Twitter account with temp mail against the rules?', 'answer' => 'Always consult Twitter/X\'s Terms of Service. inboxOro is a privacy tool — use it responsibly.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'temp-mail-for-amazon',
                'title'            => 'Temp Mail for Amazon – Sign Up Anonymously | inboxOro',
                'meta_description' => 'Use a free temp email from inboxOro to register on Amazon without your personal address. Real-time inbox, no signup, auto-deletes in 10 minutes.',
                'h1'               => 'Temp Mail for Amazon — Shop Without Sharing Your Real Email',
                'intro_text'       => '<p>Trying Amazon for the first time or testing a feature? inboxOro provides a disposable inbox that receives Amazon\'s verification email instantly, keeping your personal address safe from future marketing.</p>',
                'faq'              => json_encode([
                    ['question' => 'Can I complete an Amazon purchase with a temp email?', 'answer' => 'You can register and start exploring with a temp email, but for long-term orders and delivery confirmations, a permanent email is recommended.'],
                    ['question' => 'Does Amazon send verification emails to temp inboxes?', 'answer' => 'Yes. Amazon\'s OTP and verification emails arrive in inboxOro\'s real-time inbox within seconds of signup.'],
                    ['question' => 'Can I sign up for Amazon Prime with a temp email?', 'answer' => 'Technically yes for the initial sign-up, but Prime is a long-term subscription — using a permanent email for account recovery is strongly advised.'],
                    ['question' => 'How do I avoid Amazon marketing emails?', 'answer' => 'Use inboxOro\'s temp email for signup, then update to a permanent email in Amazon account settings only when you\'re ready to commit.'],
                    ['question' => 'Is inboxOro safe to use for Amazon signups?', 'answer' => 'Yes. inboxOro doesn\'t store any data, never asks for personal info, and deletes all emails after 10 minutes.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'temp-mail-for-verification',
                'title'            => 'Temp Mail for Verification – Instant OTP & Confirmation Inbox | inboxOro',
                'meta_description' => 'Receive any email verification code or OTP with inboxOro temp mail. Free, instant, no signup. Works for all sites. Auto-deletes in 10 min for total privacy.',
                'h1'               => 'Temp Mail for Verification — Instant OTP Codes, Zero Spam',
                'intro_text'       => '<p>Stop giving away your real email just to verify an account. inboxOro\'s temp mail receives OTP codes, confirmation links, and welcome emails from any service in real time — then disappears automatically.</p>',
                'faq'              => json_encode([
                    ['question' => 'What types of verification emails can inboxOro receive?', 'answer' => 'inboxOro can receive any standard email: OTP codes, magic links, confirmation codes, account activation emails, and more.'],
                    ['question' => 'How fast do verification emails arrive in inboxOro?', 'answer' => 'Most verification emails land in your inboxOro inbox within 5–15 seconds of being sent.'],
                    ['question' => 'Does inboxOro support HTML verification emails?', 'answer' => 'Yes. inboxOro renders both plain text and HTML emails so links and buttons are clickable.'],
                    ['question' => 'What if my OTP expires before I see it?', 'answer' => 'inboxOro updates in real time, so OTPs appear almost immediately. If one expires, simply request a new code from the site.'],
                    ['question' => 'Can I use inboxOro for two-factor authentication emails?', 'answer' => 'Yes, for 2FA codes delivered by email, inboxOro works perfectly. For SMS-based 2FA, you\'ll need a phone number instead.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'temp-mail-for-signup',
                'title'            => 'Temp Mail for Signup – Register Anywhere Without Your Real Email | inboxOro',
                'meta_description' => 'Use inboxOro temp mail to sign up for any website without sharing your personal email. Instant inbox, no registration, auto-deletes in 10 min. Stay spam-free forever.',
                'h1'               => 'Temp Mail for Signup — Register Anywhere, Stay Private',
                'intro_text'       => '<p>Every time a website asks for your email during signup, you risk spam and data leaks. inboxOro gives you a free temporary email to complete any registration privately, with everything auto-deleted after 10 minutes.</p>',
                'faq'              => json_encode([
                    ['question' => 'Why should I use temp mail for signups?', 'answer' => 'When you sign up with a real email, companies often sell or misuse it. Temp mail lets you access services without risking your inbox.'],
                    ['question' => 'Does inboxOro temp mail work on all signup forms?', 'answer' => 'It works on the vast majority of websites. A small number of services block known temporary email domains, but inboxOro regularly updates its domains.'],
                    ['question' => 'How do I copy my inboxOro address for a signup form?', 'answer' => 'Your address is displayed on the inboxOro homepage with a one-click copy button — just click and paste into any signup form.'],
                    ['question' => 'Can I use temp mail to sign up for newsletters?', 'answer' => 'Yes! Perfect for downloading a free resource or reading a gated article without subscribing your real email permanently.'],
                    ['question' => 'What happens to all the signup confirmation emails after 10 minutes?', 'answer' => 'They are permanently and automatically deleted — no logs, no traces, no backups.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'temp-mail-for-testing',
                'title'            => 'Temp Mail for Testing – Developer-Friendly Disposable Inbox | inboxOro',
                'meta_description' => 'Test email flows, OTP systems & signup forms with inboxOro. Free temp mail for developers & QA teams. Instant inbox, real-time updates, no account needed.',
                'h1'               => 'Temp Mail for Testing — The Developer\'s Disposable Inbox',
                'intro_text'       => '<p>inboxOro is a favourite among developers and QA engineers for testing email-driven features. Get a real, working inbox instantly — perfect for testing sign-up flows, OTP delivery, transactional emails, and more.</p>',
                'faq'              => json_encode([
                    ['question' => 'Can developers use inboxOro for automated testing?', 'answer' => 'inboxOro is primarily a UI-based tool. For automated pipelines, pair it with the UI for manual spot-testing or check our API plans.'],
                    ['question' => 'Can I test HTML email templates in inboxOro?', 'answer' => 'Yes! inboxOro renders HTML emails faithfully, so you can see exactly how your templates look in a real inbox.'],
                    ['question' => 'Does inboxOro work for testing transactional email services like SendGrid or Mailgun?', 'answer' => 'Absolutely. Point your transactional email service at an inboxOro address and verify delivery in real time.'],
                    ['question' => 'Is inboxOro useful for QA regression testing of signup flows?', 'answer' => 'Yes. Generate a fresh address for each test run to guarantee a clean state every time.'],
                    ['question' => 'Can I use inboxOro to test email subject lines and open rates?', 'answer' => 'For basic delivery and rendering tests, yes. For open-rate tracking you\'ll need a dedicated email testing platform.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'anonymous-email',
                'title'            => 'Anonymous Email – Send & Receive Without Revealing Yourself | inboxOro',
                'meta_description' => 'Get a free anonymous email address with inboxOro. No personal info required. Receive emails privately and let them auto-delete in 10 minutes. 100% free.',
                'h1'               => 'Anonymous Email — Your Identity Stays Your Business',
                'intro_text'       => '<p>An anonymous email from inboxOro is completely untraceable — no name, no phone, no IP stored. Generate your private inbox in one click and let everything disappear after 10 minutes.</p>',
                'faq'              => json_encode([
                    ['question' => 'What makes an email truly anonymous?', 'answer' => 'An anonymous email requires no personal information to create and leaves no identifying records behind. inboxOro collects nothing and deletes everything.'],
                    ['question' => 'Can I send emails from an inboxOro anonymous address?', 'answer' => 'inboxOro is currently a receiving service. For sending anonymous emails, pair it with an anonymous SMTP service.'],
                    ['question' => 'Is inboxOro\'s anonymous email GDPR-compliant?', 'answer' => 'inboxOro collects no personal data and stores nothing permanently, which aligns with GDPR\'s data minimisation principles.'],
                    ['question' => 'Can law enforcement trace an inboxOro anonymous email?', 'answer' => 'Since inboxOro stores no user data and auto-deletes everything in 10 minutes, there is nothing to trace or subpoena.'],
                    ['question' => 'Is anonymous email useful for whistleblowing?', 'answer' => 'For highly sensitive communications, a dedicated whistleblowing platform with end-to-end encryption is recommended alongside anonymous tools like inboxOro.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'throwaway-email',
                'title'            => 'Throwaway Email – Use Once and Forget It | inboxOro',
                'meta_description' => 'Create a free throwaway email with inboxOro in one second. No registration. Use it for any signup, OTP, or trial — then let it auto-delete in 10 minutes.',
                'h1'               => 'Throwaway Email — One Use, Zero Consequences',
                'intro_text'       => '<p>A throwaway email from inboxOro is exactly what it sounds like — use it, get what you need, and throw it away. Our system auto-deletes the inbox after 10 minutes so you don\'t even need to bother.</p>',
                'faq'              => json_encode([
                    ['question' => 'What\'s the difference between a throwaway email and a burner email?', 'answer' => 'They\'re essentially the same concept — single-use disposable addresses. Both terms describe an inbox you use once and discard.'],
                    ['question' => 'Is a throwaway email safe for online shopping?', 'answer' => 'Good for one-time purchases where you don\'t want marketing emails. For ongoing order tracking, a permanent email is more practical.'],
                    ['question' => 'How many throwaway emails can I create on inboxOro?', 'answer' => 'Unlimited. Generate as many as you need — each session gives you a fresh unique address instantly.'],
                    ['question' => 'Do throwaway emails receive spam?', 'answer' => 'They might receive a few, but since they auto-delete in 10 minutes, spam is never a long-term problem.'],
                    ['question' => 'Can I access my throwaway email from another device?', 'answer' => 'Yes. Share the email address across devices and the same inbox is accessible anywhere within the 10-minute window.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'temp-mail-for-youtube',
                'title'            => 'Temp Mail for YouTube – Create a Google Account Privately | inboxOro',
                'meta_description' => 'Sign up for YouTube/Google without your real email. inboxOro delivers a free temp inbox for instant verification. No registration needed. Auto-deletes in 10 min.',
                'h1'               => 'Temp Mail for YouTube — New Channel, No Paper Trail',
                'intro_text'       => '<p>Start a YouTube channel or create a secondary Google account privately. inboxOro\'s temp mail receives Google\'s verification email in real time — fast, free, and completely anonymous.</p>',
                'faq'              => json_encode([
                    ['question' => 'Can I use a temp email to create a Google/YouTube account?', 'answer' => 'Google often requires phone verification for new accounts, but the email step accepts inboxOro addresses. Phone verification is a separate Google security requirement.'],
                    ['question' => 'Will Google delete my account if I used a temp email?', 'answer' => 'Google doesn\'t actively audit the type of email used during signup. Your account may require phone verification for full access.'],
                    ['question' => 'Can I start a YouTube channel with an anonymous account?', 'answer' => 'Yes. Many creators maintain separate, anonymous channels. inboxOro helps you get past the email verification step privately.'],
                    ['question' => 'How fast does Google\'s verification email arrive in inboxOro?', 'answer' => 'Google\'s emails typically land in your inboxOro inbox within 5–20 seconds.'],
                    ['question' => 'Can I use temp mail for a YouTube Brand Account?', 'answer' => 'Brand Accounts are long-term assets — for those, using a permanent email you control is strongly recommended.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'temp-mail-for-github',
                'title'            => 'Temp Mail for GitHub – Register Developer Accounts Privately | inboxOro',
                'meta_description' => 'Use inboxOro temp mail to sign up for GitHub without your personal email. Instant inbox, real-time delivery, no registration. Auto-deletes in 10 minutes.',
                'h1'               => 'Temp Mail for GitHub — Commit to Privacy',
                'intro_text'       => '<p>Create a secondary GitHub account or test your email integration without using your personal address. inboxOro delivers GitHub\'s verification email in seconds — no account needed on our side.</p>',
                'faq'              => json_encode([
                    ['question' => 'Does GitHub accept temp email addresses?', 'answer' => 'Yes. GitHub sends verification emails to any valid inbox, and inboxOro\'s addresses receive them successfully in real time.'],
                    ['question' => 'Can I use temp mail to test GitHub Actions email notifications?', 'answer' => 'Yes! inboxOro is popular among developers for testing CI/CD notification emails without cluttering a permanent inbox.'],
                    ['question' => 'What happens to my GitHub account when the temp email expires?', 'answer' => 'Your GitHub account remains active. Update your email in GitHub settings before the temp address expires if you want long-term access.'],
                    ['question' => 'Can I receive GitHub pull request and issue notifications on temp mail?', 'answer' => 'Yes, within the 10-minute window. For ongoing GitHub notifications, use a permanent email address.'],
                    ['question' => 'Is inboxOro useful for open-source contributors who want privacy?', 'answer' => 'Absolutely. Many privacy-conscious contributors use a temp email for initial signup and then update to a pseudonymous permanent address.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'no-signup-email',
                'title'            => 'No Signup Email – Instant Inbox With Zero Registration | inboxOro',
                'meta_description' => 'Get a real email inbox with no signup, no password, no account. inboxOro generates your address instantly. Perfect for OTPs & verifications. Auto-deletes in 10 min.',
                'h1'               => 'No Signup Email — A Real Inbox in Under a Second',
                'intro_text'       => '<p>Why sign up for an email just to sign up for something else? inboxOro gives you a fully functional inbox the moment you land on the page — no forms, no passwords, no waiting.</p>',
                'faq'              => json_encode([
                    ['question' => 'Do I really not need to create an account on inboxOro?', 'answer' => 'Correct. inboxOro requires zero registration. Your temporary inbox is generated automatically the moment you visit the site.'],
                    ['question' => 'How is a no-signup email different from a regular email service?', 'answer' => 'Traditional email services require a name, password, phone, and often verification. inboxOro needs nothing — your inbox is ready instantly.'],
                    ['question' => 'Is a no-signup email secure?', 'answer' => 'It\'s private and anonymous. Since there\'s no account attached, there\'s nothing to hack. All data deletes automatically after 10 minutes.'],
                    ['question' => 'Can I access the no-signup inbox from multiple devices?', 'answer' => 'Yes. Share the email address with another device and the inbox is accessible anywhere during the 10-minute window.'],
                    ['question' => 'Do I need to install anything to use inboxOro?', 'answer' => 'No installation needed. inboxOro is fully browser-based and works on desktop, mobile, and tablet.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'spam-free-email',
                'title'            => 'Spam-Free Email – Keep Your Inbox Clean with inboxOro',
                'meta_description' => 'Tired of spam? Use inboxOro\'s temp email for every signup and keep your real inbox spam-free forever. Free, instant, auto-deletes in 10 minutes. No registration.',
                'h1'               => 'Spam-Free Email — Stop Spam Before It Starts',
                'intro_text'       => '<p>Every time you sign up with your real email, you risk a flood of marketing and spam. inboxOro intercepts the verification, keeps your real inbox clean, and auto-deletes the temp address after 10 minutes.</p>',
                'faq'              => json_encode([
                    ['question' => 'How does inboxOro help me avoid spam?', 'answer' => 'By giving websites a temporary address instead of your real one, you stop spam at the source. When the temp email expires, no further emails can reach it.'],
                    ['question' => 'What if I still want newsletters after trying them out?', 'answer' => 'Use inboxOro to check the first email, then if you like the content, re-subscribe with your real email. Best of both worlds.'],
                    ['question' => 'Can spam emails follow me from a temp inbox to my real one?', 'answer' => 'No. Since your real email is never shared, there is no connection between the temp inbox and your personal address.'],
                    ['question' => 'Does inboxOro filter spam in the temp inbox?', 'answer' => 'inboxOro shows all incoming emails, including potential spam. Since the inbox auto-deletes in 10 minutes, spam is never a lasting concern.'],
                    ['question' => 'How much spam does the average person receive after signup?', 'answer' => 'Studies show most websites send at least 3–5 marketing emails per week after signup. inboxOro helps you avoid that entirely.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'privacy-email',
                'title'            => 'Privacy Email – Browse & Sign Up Without Being Tracked | inboxOro',
                'meta_description' => 'Protect your online identity with inboxOro\'s privacy-focused temp email. No personal data, no tracking, auto-deletes in 10 min. Free and instant — no signup required.',
                'h1'               => 'Privacy Email — Your Real Inbox Is None of Their Business',
                'intro_text'       => '<p>inboxOro is built for privacy first. Every temporary email address we generate is anonymous, unlinked to any identity, and automatically erased — because your personal data should stay personal.</p>',
                'faq'              => json_encode([
                    ['question' => 'Does inboxOro log my IP address or browsing data?', 'answer' => 'inboxOro is designed with minimal data collection as a core principle. No personal data is required or retained beyond the active session.'],
                    ['question' => 'Can companies track me through an inboxOro email?', 'answer' => 'Since the email auto-deletes and is never linked to your identity, tracking through inboxOro is essentially impossible.'],
                    ['question' => 'Is inboxOro safer than email aliases?', 'answer' => 'Both tools serve privacy, but differently. Email aliases forward to your real address, while inboxOro is a completely standalone, self-destructing inbox.'],
                    ['question' => 'Do advertising networks benefit from inboxOro data?', 'answer' => 'No. inboxOro operates entirely without advertising networks or third-party trackers in its core product.'],
                    ['question' => 'Is inboxOro a good choice for privacy-conscious professionals?', 'answer' => 'Yes. Journalists, researchers, security professionals, and privacy advocates regularly use disposable email services like inboxOro for sensitive signups.'],
                ]),
                'is_active'        => true,
            ],
            [
                'slug'             => 'email-for-otp',
                'title'            => 'Temp Email for OTP – Receive One-Time Passwords Instantly | inboxOro',
                'meta_description' => 'Get your OTP in seconds using inboxOro\'s free temp email. Works for all sites sending email-based OTPs. Real-time inbox, no signup, auto-deletes in 10 minutes.',
                'h1'               => 'Temp Email for OTP — One-Time Passwords Delivered in Seconds',
                'intro_text'       => '<p>Need an OTP fast without using your real email? inboxOro\'s live inbox receives one-time passwords and verification codes from any website the moment they\'re sent — no delays, no spam, no trace.</p>',
                'faq'              => json_encode([
                    ['question' => 'How quickly do OTP emails arrive in inboxOro?', 'answer' => 'OTP emails typically appear in your inboxOro inbox within 5–15 seconds of being sent by the service.'],
                    ['question' => 'Does inboxOro work for email OTPs from banks?', 'answer' => 'For banking and financial services, we strongly recommend using your permanent registered email, as these services require account continuity.'],
                    ['question' => 'What if my OTP expires before I open inboxOro?', 'answer' => 'inboxOro updates in real time, so OTPs appear almost instantly. If one expires, request a new code from the website.'],
                    ['question' => 'Can I use inboxOro for OTPs on multiple services simultaneously?', 'answer' => 'Yes, though each service should use a separate inboxOro address to keep inboxes clean and avoid confusion.'],
                    ['question' => 'Are email OTPs safer than SMS OTPs?', 'answer' => 'Both have trade-offs. Email OTPs avoid SIM-swapping risks but can be intercepted if your email is compromised. inboxOro\'s temp addresses reduce that risk.'],
                ]),
                'is_active'        => true,
            ],
        ];

        foreach ($pages as $page) {
            SeoPage::updateOrCreate(
                ['slug' => $page['slug']],
                $page
            );
        }

        $this->command->info('✅ 25 SEO Pages seeded successfully!');
    }
}